package yuma140902.mimic;

import java.io.File;
import java.util.logging.LogManager;
import java.util.logging.Logger;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.common.config.Configuration;

@Mod(modid = ModMimic.MOD_ID, useMetadata = true)
public class ModMimic {

	public static final String MOD_ID = "mimic";
	public static final String MOD_NAME = "擬態ブロックMOD";
	public static final String MOD_VERSION = "mc1.7.10_1.0.0";
	public static final String CONFIG_FILE_NAME = "config\\" + MOD_NAME + ".cfg";
	
	
	@Mod.Metadata
	public static ModMetadata modMetadata;
	
	@Mod.Instance
	public static ModMimic INSTANCE;
	
	@SidedProxy(clientSide = "yuma140902.mimic.ClientProxy", serverSide = "yuma140902.mimic.CommonProxy")
	public static CommonProxy proxy;
	
	public static Logger logger = LogManager.getLogManager().getLogger(MOD_ID);
	
	private void loadModMetadata(ModMetadata modMetadata) {
		modMetadata.modId = MOD_ID;
		modMetadata.name = MOD_NAME;
		modMetadata.version = MOD_VERSION;
		modMetadata.authorList.add("yuma140902");
		modMetadata.description = "ブロックの硬さ、見た目、適正ツール、ピストンで押された時の挙動、などを、他のブロックからコピペして擬態できるブロックを追加します";
		modMetadata.autogenerated = false;
	}
	
	private void loadConfig() {
		Configuration cfg = new Configuration(new File(CONFIG_FILE_NAME));
		try {
			cfg.load();
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		finally {
			cfg.save();
		}
	}
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		loadModMetadata(modMetadata);
		loadConfig();
		
//		MyBlocks.register();
//		MyItems.register();
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event) {
//		Recipes.register();
//		WorldGenerators.register();
	}
}
